batch_size: 1024
epochs: 1
model: "super_deit_s"
multi_reso: false
input_size: 224
drop: 0.0
drop_path: 0.1
model_ema: true
model_ema_decay: 0.99996
model_ema_force_cpu: false
opt: "adamw"
opt_eps: 1.0e-8
opt_betas: null
clip_grad: null
momentum: 0.9
weight_decay: 0.05
sched: "cosine"
lr: 0.0005
lr_noise: null
lr_noise_pct: 0.67
lr_noise_std: 1.0
warmup_lr: 1.0e-6
min_lr: 1.0e-5
decay_epochs: 30
warmup_epochs: 5
cooldown_epochs: 10
patience_epochs: 10
decay_rate: 0.1
color_jitter: 0.4
aa: "rand-m9-mstd0.5-inc1"
smoothing: 0.1
train_interpolation: "bicubic"
repeated_aug: true
reprob: 0.25
remode: "pixel"
recount: 1
resplit: false
mixup: 0.8
cutmix: 1.0
cutmix_minmax: null
mixup_prob: 1.0
mixup_switch_prob: 0.5
mixup_mode: "batch"
teacher_model: "regnety_160"
teacher_path: ""
distillation_type: "none"
distillation_alpha: 0.5
distillation_tau: 1.0
finetune: ""
data_path: "ImageNet"
data_set: "IMNET"
inat_category: "name"
output_dir: "ravit/output112"
device: "cuda"
seed: 0
resume: "ravit/output112/model_best.pth"
autoresume: false
start_epoch: 0
eval: true
dist_eval: true
num_workers: 10
pin_mem: true
world_size: 2
dist_url: "env://"
wandb_project: ""
wandb_name: ""
rank: 0
gpu: 0
distributed: true
dist_backend: "nccl"
